version: 2.1

defaults: &defaults
  working_directory: ~/dotfiles
  environment:
    BASH_ENV: local.env
  docker:
    - image: cimg/base:stable

test: &test
  steps:
    - run:
        name: Assign Test Variable Export
        command: echo 'export ARM_VAR=${TEST_ARM_VAR}' >> $BASH_ENV

prod: &prod
  steps:
    - run:
        name: Assign Prod Variable Export
        command: echo 'export ARM_VAR=${PROD_ARM_VAR}' >> $BASH_ENV

jobs:
  say-hello-test:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Assign Test Variable Export
          command: echo 'export ARM_VAR=${TEST_ARM_VAR}' >> $BASH_ENV
      - run:
          name: Show Test Message
          command: python3 showstuff.py
  say-hello-prod:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Assign Prod Variable Export
          command: echo 'export ARM_VAR=${PROD_ARM_VAR}' >> $BASH_ENV
      - run:
          name: Show Prod Message
          command: python3 showstuff.py

workflows:
  say-hello-flow:
    jobs:
      - say-hello-test
      - say-hello-prod
