version: 2.1

defaults: &defaults
  working_directory: ~/dotfiles
  environment:
    BASH_ENV: local.env
  docker:
    - image: cimg/base:stable

test: &test
  steps:
    - run:
        command: echo "export ARM_VAR=${TEST_ARM_VAR}" >> $BASH_ENV

prod: &prod
  steps:
    - run:
        command: echo "export ARM_VAR=${PROD_ARM_VAR}" >> $BASH_ENV

jobs:
  say-hello-test:
    <<: *defaults
    <<: *test
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Show Test Message
          command: echo ${ARM_VAR}
  say-hello-prod:
    <<: *defaults
    <<: *prod
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Show Prod Message
          command: echo ${ARM_VAR}

workflows:
  say-hello-flow:
    jobs:
      - say-hello-test
      - say-hello-prod
