version: 2.1
testvars: &testvars
  steps:
    - run:
        command: echo 'export ARM_VAR="${TEST_ARM_VAR}"' >> $BASH_ENV
prodvars: &prodvars
  steps:
    - run:
        command: echo 'export ARM_VAR="${PROD_ARM_VAR}"' >> $BASH_ENV
jobs:
  say-hello-test:
    docker:
      - image: cimg/base:stable
    <<: *testvars
    steps:
      - checkout
      - run:
          name: show test vars
          command: echo ${ARM_VAR}
  say-hello-prod:
    docker:
      - image: cimg/base:stable
    <<: *prodvars
    steps:
      - checkout
      - run:
          name: show prod vars
          command: echo ${ARM_VAR}
workflows:
  say-hello-test-flow:
    jobs:
      - say-hello-test
  say-hello-prod-flow:
    jobs:
      - say-hello-prod
