version: 2.1
defaults: &defaults
  working_directory: ~/dotfiles
  environment:
    TEST_VAR: $MY_FIRST_SECRET
jobs:
  say-hello:
    <<: *defaults
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: show vars
          command: |
            echo $MY_FIRST_SECRET
            echo $TEST_VAR
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
