version: 2.1

testvars: &testvars
  environment:
    BASH_ENV: local.env
  steps:
    - run:
        name: Set Test Variable
        command: echo "export ARM_VAR="${TEST_ARM_VAR}" >> $BASH_ENV
  docker:
    - image: cimg/base:stable

prodvars: &prodvars
  environment:
    BASH_ENV: local.env
  steps:
    - run:
        name: Set Prod Variable
        command: echo "export ARM_VAR=${PROD_ARM_VAR}" >> $BASH_ENV
  docker:
    - image: cimg/base:stable

jobs:
  say-hello-test:
    <<: *testvars
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Show Test Message
          command: echo ${ARM_VAR}
  say-hello-prod:
    docker:
      - image: cimg/base:stable
    <<: *prodvars
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Show Prod Message
          command: echo ${ARM_VAR}

workflows:
  say-hello-flow:
    jobs:
      - say-hello-test
      - say-hello-prod
